name: Whatsapp
version: "1.2.4"
slug: whatsapp_addon
description: Whatsapp addon for send message from Home Assistant
url: "https://github.com/giuseppecastaldo/ha-addons/tree/main/whatsapp_addon"
homeassistant_api: true
hassio_api: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - config:rw
options:
  clients:
    - default
schema:
  clients:
    - str
